### ISSUE TITLE
changelogger shows an "Platform link invalid"

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [Isigiel/changelogger#1]
changelogger shows an "Platform link invalid"
no further comments...

**Comment by heddendorp** [comment]
Hello, thank you for opening this issue, the proxy I'm using recently was switched to ssl and a couple of dns hiccups occurred.
Please try again now, everything should work fine.

**Comment by 5t0rmr1d3r** [comment]
hello, thank you for this great tool!
sadly, issue still exist, also with the example link.

**Comment by heddendorp** [comment]
Hey, are you on discord by chance?
I cannot seem to reproduce that issue and would like to investigate what is happening on your side.
I think I actually did find something that was off, should be fixed for real now.

**Comment by 5t0rmr1d3r** [comment]
Weird, on my mobile it works now. Test it in the evening on my PC.

**Comment by heddendorp** [comment]
I'm closing this, assuming everything works fine again
