### ISSUE TITLE
Any chance for another fix for Technic API?

### ISSUE THREAD

**Issue by xJon** [Isigiel/changelogger#3]
Since https://github.com/Isigiel/changelogger/commit/6e1ec41ccd071cf15208ca1aa4a7a3e8da4c3e98 last year Changelogger is still down. Would be nice to have it if it's not a big bother!

**Comment by heddendorp** [comment]
The project should be fixed for now
A permanent fix is outlined in https://github.com/Isigiel/changelogger/blob/gh-pages/js/app.js#L40
